### ISSUE TITLE
Server uses increasing amount of RAM

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-server#145]
We’ve being using OMM without trouble for a few months, all was well. But the process Vmmem (virtual machine memory) now takes more than 12Gb of RAM. I thought this might be temporary because docker had been running for a while so I restarted it, upon starting Vmmem reached 3GB, next day, back to 12GB. Fortunately, the experiments themselves don’t seem to be slowed down.
![MemorySaturation](https://user-images.githubusercontent.com/50901388/212464092-35e0c80a-a2e1-46e4-92ff-04a44be5ca74.PNG)
![MemorySaturation_starting_docker](https://user-images.githubusercontent.com/50901388/212464093-1b1691b1-a67d-46c3-b691-b7e6905c403a.PNG)

**Comment by smathot** [comment]
Good to hear that you've been running it smoothly!

I suspect that the excessive memory use is due to WSL (the Windows Subsystem for Linux), which seems to have a habit of reserving excessive amounts of memory for itself. You can set a limit for this, and I'll take a look at this soon. In the meanwhile: do you experience any adverse side effects? My guess is that running other applications on the system is sluggish because OMM (or rather WSL) has reserved so much memory, but that OMM itself is running fine. Can you confirm this?

**Comment by nclaidiere** [comment]
That's exactly what's happening, OMM seems fine but anything else is super slow.

I found these:
https://www.bleepingcomputer.com/news/microsoft/windows-10-wsl2-now-allows-you-to-configure-global-options/
https://medium.com/@lewwybogus/how-to-stop-wsl2-from-hogging-all-your-ram-with-docker-d7846b9c5b37

and created a .wslconfig file with:
[wsl2]
memory=5GB

So far the memory is around 5.5GB so I don't know if it's working or not... I'll let you know if it goes higher.

Thanks for your quick feedback!

**Comment by dschreij** [comment]
Nice that everything is running as it should be.
As Sebastiaan said, this is most likely due to memory consumption of the WSL, which Docker is running on. In an idle state I already have a usage of 8GB, but that often goes up to 16GB+ levels as well when under heavy usage

![image](https://user-images.githubusercontent.com/689044/212471825-9821b047-d0e7-46b5-895f-9e67faf48281.png)

but for my PC that does not have any negative side effects because it has 32GB of RAM. With lesser amounts of RAM, WSL should limit its memory usage as well to some sensible value, but if you're not happy with it, you can always configure this using a wsl.conf file. See https://www.aleksandrhovhannisyan.com/blog/limiting-memory-usage-in-wsl-2/ for more information.

**Comment by nclaidiere** [comment]
Ok, I just checked and have 16GB of RAM, so that might not be enough then. Do you have any recommendations regarding the values in the config file? RAM? nb of processors? SWAP memory? (whatever that is?)

**Comment by nclaidiere** [comment]
Hi, thanks for your quick replies, I did not manage to limit memory usage despite trying various different options. However, I realised I had not updated docker to the latest version, I did and now it stays around 5GB. So I guess this was just a bug in one version of docker... Thanks again!

**Comment by dschreij** [comment]
If this remains a problem, it's always an option to install mysql natively on the real server. This will take a little bit of effort but it may pay off. In other places, I would still use Docker because it's much easier to setup and use.
