### ISSUE TITLE
Duplicated trials: same job done twice at the same time

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-server#153]
Hi,

Over the last few experiments we noticed that we had the same trial repeated twice for no apparent reason.

Here is a sample of such data:
![image](https://github.com/open-cogsci/omm-server/assets/50901388/6f69348f-5670-4037-9474-26b9870e90a2)

The same individual is doing 2 trials in rapid succession (usually <10secs), the job id is the same, the iteration increases correctly, but not the nb of jobs done for instance. Notice that some of them are just impossible, so ARIELLE iteration 43 and 44 are 4 secs apart but trial 43 took more than 8 secs.

So here is my theory, monkey A starts a trial in a client 1, monkey B walks in and chase A away. A walks in the next client (2) and starts a new trial while B is still finishing the trial started by A in client 1. This would happen at a very low frequency, as we observe, and could explain it.

Unfortunately, in relation to #149 we do not have any information on where the monkeys are doing their trials.

Still, here is a question: when a job is opened by an individual, can that individual open a new one before the first job is finished? or is that just impossible? (in which case I need to look elsewhere)

**Comment by smathot** [comment]
I suspect your analysis is correct. @dschreij can you confirm that the `currentjob` end point indeed gets the next job that is either pending or started? (i.e. just not those that are finished.)

- https://github.com/open-cogsci/omm-server/blob/master/app/Controllers/Http/ParticipantController.js#L505

Now that we have a reasonable hypothesis about where this comes from, my suggestion would be to deal with this at the level of the analysis rather than change the behavior of the system. Specifically, jobs where this happens will be characterized by very high response times, right? And those should be excluded anyway, I assume, in which case there is practically speaking no issue. Or are there situations where this is problematic?

**Comment by nclaidiere** [comment]
Interesting question, to some extent this gives us an idea of how frequently a baboon is replaced by another undetected. Ideally, it would be great to make sure that the same baboon is present at the beginning and end of the experiment. But this is beyond the present discussion. So I think you're right, if we are certain that this is what is happening, then we can safely remove the duplicated trials during analysis.
