### ISSUE TITLE
The announce endpoint skips a study when all jobs have been done but are reset to pending

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-server#88]
The attentional capture experiment consists of a practice phase of 4 trials, followed by an experimental phase of another 4 trials. After the practice phase, the accuracy during practice is calculated, and when this is less than .75, the practice jobs are set back to pending so that the practice phase is repeated. This works perfectly.

However, when the job table only consists of 4 trials of practice phase (and no experimental trials), things go wrong. The jobs are still reset back to pending, and in the server interface you can also see that the participant hasn't finished the study yet. But the study is no longer returned by the announce endpoint.

I suspect that the announce endpoint uses an incorrect logic to determine which studies are still open, not taking into account that a job may have data but still be pending.

Ping @nclaidiere

**Comment by dschreij** [comment]
This is because the study has its own status of being completed or not. I think it is too much of a performance impact to check the completion status of the study by checking if the status of all individual jobs are set to completed. Especially since there could easily be 10000 jobs or so?
So, this is checked and adapted whenever a job's status changes, but apparently not consistently enough as this situation occurs. The completion check is done in https://github.com/open-cogsci/omm-server/blob/master/app/Models/Study.js#L329-L361, so the mistake must be in here (even though it worked correctly for me after some testing last time), or the fact that the function isn't called where it should somewhere in the code.

Which endpoints are you using to change the jobs' statuses?

**Comment by dschreij** [comment]
Hmmm that calls https://github.com/open-cogsci/omm-server/blob/v0.5.4/app/Controllers/Http/StudyController.js#L813-L849 and I see no mention of the `Study.checkIfFinished()` function there :see_no_evil: 
I cannot really recall how I changed the status of a study when I tested the function above... I´ll look into this.
