### ISSUE TITLE
Add generic data that is associated with a participant and/ or a study (or neither)

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-server#95]
@nclaidiere provided some complicated scenarios in which jobs need to be repeated at predictable moments while the rest of the jobs are executed in a random order. This is not easily implemented with the end-points that currently exist. I feel that having a generic data field is the easiest and most flexible way to accommodate such scenarios, because this data could be used as a persistent store for various forms of bookkeeping.

*Update:* I initially envisioned this as being associated with a study and a participant. But I think it can be implemented more generically at no additional cost by having different levels of generic data:

- Associated with a study and a participant
- Associated with a study and shared across participants in that study
- Associated with a participant and shared across all studies for that participants
- Global (shared across all studies and participants)

More specifically, I'm thinking of two endpoints, one `get` and one `patch` (?), to get the data for a participant and a study. The data itself would just be text. The end point could be:

```
/participants/{identifier}/{studyID}/studydata
```

… where `studyID` and `identifier` could for example be set to null in the case of generic data is shared across respectively studies or participants (or both).

This is somewhat inspired by JATOS's concept of batch-session data. However, I don't think we need all the complicated versioning that is implemented there. Just a simple way to get and set text data would be sufficient.

Does this make sense?

**Comment by dschreij** [comment]
The multiple levels complicates things quite a bit, as the data will need to be stored in different tables, if this is to be done in a tidy way, i.e.

- Associated with a study and a participant --> Store in participations table
- Associated with a study and shared across participants in that study --> Store in study table
- Associated with a participant and shared across all studies for that participants -> Stored in participants table (basically this one is already there, as you already can store random data in a participant record?)
- Global (shared across all studies and participants) --> For this a new table needs to be created, as I cannot think of any appropriate table to currently store this.

> More specifically, I'm thinking of two endpoints, one get and one patch (?), to get the data for a participant and a study. The data itself would just be text. The end point could be: `/participants/{identifier}/{studyID}/studydata`

This endpoint seems ok, although it is very uncommon to send `null` values as URL parameters to REST endpoint. The reason is likely that the null values in `/participants/null/null/studyData` can only be interpreted as strings containing "null". This is not a showstopper of course, as we can check for strings having the value "null", but convention would be to just create appropriate endpoints for each different type of data storage. These endpoints can of course point to the same controller function, so this does not imply that there needs to be duplicate logic.

All in all, even though this seems to be quite a simple feature, it involves quite some work and we need to think this through before we start implementing it. I am not reluctant at all to work on this, but with the available time I have at the moment, it will be hard to complete this anytime soon.

**Comment by smathot** [comment]
My initial idea for implementing this was to simply have a table for generic data with one field for the data itself, which would be a JSON string, one field for the associated participant (which is null if it's not specific to a participant) and one field for the associated study (which is also null if it's not specific to a study). That would be fairly straightforward, right? Is there a downside to implementing it like this?

**Comment by dschreij** [comment]
No a table like that is a good idea actually. The mentioned problems with the endpoint remains though. We should try to prevent sending 'null' as path arguments. We could make them query params though, so you would get something like

```
/studydata?participant=X&study=Y
```
and then you can leave away params when desired.

**Comment by smathot** [comment]
Ok :+1:
